management/urls.py
from django.urls import path
from . import views

app_name = 'management'

urlpatterns = [
    path('<str:backend_key>/', views.overview, name='overview'),
    path('<str:backend_key>/copy/<int:site_id>/', views.copy, name='copy'),
    path('<str:backend_key>/edit/<int:site_id>/', views.edit, name='edit'),
    path('<str:backend_key>/delete/<int:site_id>/', views.delete, name='delete'),
    path('', views.overview, name='overview'),
    path('<str:backend_key>/admin_email_addresses', views.admin_email_addresses, name='admin_email_addresses')
]

pleio_control/urls.py
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib import admin

from two_factor.urls import urlpatterns as tf_urls
from management.urls import urlpatterns as management_urls
from administration.urls import urlpatterns as administration_urls

import core.views as core_views
import management.views as management_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', core_views.home, name='home'),
    path('tasks/', core_views.tasks, name='tasks'),
    path('tasks/status', core_views.task_status, name='task_status'),
    path('account/logout/', core_views.logout, name='logout'),
    path('', RedirectView.as_view(url='home')),
    path('', include(tf_urls)),
    path('management/', include('management.urls')),
    path('administration/', include('administration.urls')),
]

management/models.py
from django.db import models

# Create your models here.

management/forms.py
from django import forms
from django.core.exceptions import ValidationError


class CopyForm(forms.Form):
    def __init__(self, context, *args, **kwargs):
        super(CopyForm, self).__init__(*args, **kwargs)
        self.context = context
        self.fields['destination'].choices = [ (v.key, v.name) for v in context['backends'].values() if v.is_writable ]

        if context.get('overwrite'):
            self.fields['overwrite'] = forms.BooleanField(label='A site with this key already exists. Are you sure you want to overwrite the site?')

    destination = forms.ChoiceField(label='Bestemming', choices=[], widget=forms.Select(attrs={'class' : 'form-control'}))
    key = forms.CharField(label='Sleutel', widget=forms.TextInput(attrs={'class' : 'form-control'}))
    host = forms.CharField(label='Hostnaam', widget=forms.TextInput(attrs={'class' : 'form-control'}))

    def clean_key(self):
        data = self.cleaned_data
        if (data.get('destination') == self.context['backend'].key) and (data.get('key') == self.context['site'].key):
            raise ValidationError("Cannot copy a site to itself.")
        return data.get('key')


class EditForm(forms.Form):
    CHOICES = (
        ('test', 'Test'),
        ('prod', 'Productie'),
    )

    def __init__(self, context, *args, **kwargs):
        super(EditForm, self).__init__(*args, **kwargs)

    key = forms.CharField(label='Sleutel', widget=forms.TextInput(attrs={'class' : 'form-control', 'readonly': True}))
    host = forms.CharField(label='Hostnaam', widget=forms.TextInput(attrs={'class' : 'form-control'}))
    enabled = forms.BooleanField(label='Actief', required=False, widget=forms.CheckboxInput(attrs={'class': 'form-control'}))
    env = forms.ChoiceField(label='Omgeving', choices=CHOICES, widget=forms.Select(attrs={'class': 'form-control'}))

class DeleteForm(forms.Form):
    def __init__(self, context, *args, **kwargs):
        super(DeleteForm, self).__init__(*args, **kwargs)
        self.context = context

    key = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control'}))

    def clean_key(self):
        value = self.cleaned_data.get('key')
        if value != self.context['site'].key:
            raise ValidationError("Please fill in the key of the site.")
        return value

management/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.http import Http404
from django.shortcuts import render, redirect
from django.conf import settings
from sqlalchemy.exc import OperationalError
from sqlalchemy.sql import select

from . import elgg_models
from .lib import Manager
from .forms import CopyForm, EditForm, DeleteForm
from .tasks import copy_site, delete_site, diskspace

def overview(request, backend_key=None):
    return render(request, 'overview.html', _get_context(backend_key))

def copy(request, backend_key, site_id):
    context = _get_context(backend_key, site_id)

    if not request.POST:
        diskusage_task = diskspace.delay(backend_key, site_id)

        form = CopyForm(context)
        context['form'] = form
        context['db_size'] = context['backend'].get_site_db_size(site_id)
        context['disk_usage_task'] = diskusage_task.id
        return render(request, 'copy.html', context)

    if request.POST.get('overwrite'):
        context['overwrite'] = True

    form = CopyForm(context, request.POST)

    if not form.is_valid():
        context['form'] = form
        return render(request, 'copy.html', context)

    data = form.cleaned_data

    try:
        destination_backend = context['backends'][data['destination']]
    except KeyError:
        raise Http404("Destination backend does not exist")

    if destination_backend.key_exists(data['key']) and not data.get('overwrite'):
        context['overwrite'] = True
        context['form'] = CopyForm(context, request.POST)
        return render(request, 'copy.html', context)

    copy_site.delay(backend_key, site_id, data['destination'], data['key'], data['host'])

    messages.add_message(request, messages.SUCCESS, 'The copy is scheduled successfully.')
    return redirect('management:overview', backend_key=backend_key)

def edit(request, backend_key, site_id):
    context = _get_context(backend_key, site_id)
    backend = context['backend']

    if request.POST:
        form = EditForm(context, request.POST)
        if form.is_valid():
            try:
                backend.edit_site(site_id, form.cleaned_data)
                messages.add_message(request, messages.SUCCESS, 'The site is edited successfully.')
            except NotImplementedError:
                messages.add_message(request, messages.ERROR, 'Could not edit site as the function is not implemented.')
            return redirect('management:overview', backend_key=backend_key)
    else:
        form = EditForm(context, context['site'].get_values())

    context['form'] = form
    return render(request, 'edit.html', context)

def delete(request, backend_key, site_id):
    context = _get_context(backend_key, site_id)
    backend = context['backend']

    if request.POST:
        form = DeleteForm(context, request.POST)
        if form.is_valid():
            delete_site.delay(backend_key, site_id, context['site'].host)
            messages.add_message(request, messages.SUCCESS, 'The deletion of the is scheduled successfully.')
            return redirect('management:overview', backend_key=backend_key)
    else:
        form = DeleteForm(context)

    context['form'] = form
    return render(request, 'delete.html', context)

def _get_context(backend_key=None, site_id=None):
    manager = Manager.Instance()

    context = {
        'backends': manager.backends
    }

    if backend_key:
        try:
            context['backend'] = manager.backends[backend_key]
        except KeyError:
            raise Http404("Backend does not exist")

    if site_id:
        try:
            context['site'] = manager.backends[backend_key].get_site(site_id)
        except Exception:
            raise Http404("Site does not exist")

    return context


def admin_email_addresses(request, backend_key):
    admin_email_addresses = []
    manager = Manager.Instance()

    source_backend = manager.backends[backend_key]
    sites = source_backend.get_sites()

    for site in sites:
        try:
            source_site = source_backend.get_site(site['id'])
        except Exception:
            continue

        if source_site.has_pleio_guid:
            query = select([elgg_models.users_entity_with_pleio_guid]).where(elgg_models.users_entity_with_pleio_guid.c.admin == 'yes')
            rows = source_site.connection.execute(query)
        else:
            query = select([elgg_models.users_entity_without_pleio_guid]).where(elgg_models.users_entity_without_pleio_guid.c.admin == 'yes')
            rows = source_site.connection.execute(query)

        admin_email_addresses = admin_email_addresses + [user['email'] for user in rows]

    return render(request, 'admin_email_addresses.html', {'admin_email_addresses': sorted(list(set(admin_email_addresses)))})

management/templates/_management_base.html
{% extends '_base.html' %}

{% block content %}
    <div class="row">
        <div class="col-sm-2">
            {% include 'partials/sidenav.html' %}
        </div>
        <div class="col-sm-10">
            {% block management_content %}{% endblock %}
        </div>
    </div>
{% endblock %}

management/templates/admin_email_addresses.html
{% extends '_management_base.html' %}

{% block management_content %}

        {% for email in admin_email_addresses %}
            {{ email }}, 
        {% endfor %}

{% endblock %}

management/templates/copy.html
{% extends '_management_base.html' %}

{% block management_content %}
    <h1>Site kopieren</h1>
    <form method="POST" action="." class="form">
        {% csrf_token %}
        <p>Je staat op het punt om de site <b>{{ site.host }}</b> naar een nieuwe bestemming te kopieren. Selecteer de bestemming, bedenk een nieuwe sleutel en vul de nieuwe hostnaam in voor de kopie.</p>

        <h4>Statistieken</h4>
        <p>
            Database:  <strong {% if db_size > 500 %}style="color:red"{% endif %}>{{ db_size|floatformat }} MB</strong> |
            Files: <strong><span id="disk_usage">...</span> MB</strong> |
            <strong><span id="disk_free">...</span> GB</strong> beschikbaar
        </p>

        <p style="color:  red; display: none">Let op, dit is een grote site. Deze kopieer actie kan het best op een rustige moment worden uitgevoerd (vroeg in de ochtend, avond of weekend). Dit beperkt overlast en vertraging op andere productie sites.</p>

        <div class="form-group">
            {{ form }}
        </div>
        <a href="{% url 'management:overview' backend.key %}" class="btn btn-secondary">Annuleren</a>
        <button type="submit" class="btn btn-primary">Kopieren</button>
    </form>

{% endblock %}

{% block scripts %}
<script type="application/javascript">
    var getJSON = function(url, callback) {
        var xhr = new XMLHttpRequest();
        xhr.open('GET', url, true);
        xhr.responseType = 'json';
        xhr.onload = function() {
            var status = xhr.status;
            if (status == 200) {
                callback(null, xhr.response);
            } else {
                callback(status);
            }
        };
        xhr.send();
    };


    setInterval(function() {
        getJSON('/tasks/status?task_id={{ disk_usage_task }}', function(status, result) {
            if (result) {
                if (result['finish']) {
                    document.getElementById('disk_usage').textContent = result['finish']['usage'];
                    document.getElementById('disk_free').textContent = result['finish']['free'];
                }
            }
        });
    }, 1000);
</script>
{% endblock %}

management/templates/delete.html
{% extends '_management_base.html' %}

{% block management_content %}
    <h1>Site verwijderen</h1>
    <form method="POST" action="." class="form">
        {% csrf_token %}
        <p>Vul de sleutel van de site <b>{{ site.key }}</b> in om de site te verwijderen.</p>
        <div class="form-group">
            {{ form }}
        </div>
        <a href="{% url 'management:overview' backend.key %}" class="btn btn-secondary">Annuleren</a>
        <button type="submit" class="btn btn-danger">Verwijderen</button>
    </form>
{% endblock %}

management/templates/edit.html
{% extends '_management_base.html' %}

{% block management_content %}
    <h1>Site wijzigen</h1>
    <form method="POST" action="." class="form">
        {% csrf_token %}
        <div class="form-group">
            {{ form }}
        </div>
        <a href="{% url 'management:overview' backend.key %}" class="btn btn-secondary">Annuleren</a>
        <button type="submit" class="btn btn-primary">Wijzigen</button>
    </form>
{% endblock %}

management/templates/overview.html
{% extends '_management_base.html' %}

{% block management_content %}
    {% if backend %}

        <h1>{{ backend.name }}</h1>
        <h4>Mail adressen deelsite beheerders</h4>
        <a href="{% url 'management:admin_email_addresses' backend.key %}">E-mail adressen</a>
        <br /><br /><br />

        <h4>Sites beheren</h4>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Sleutel</th>
                    <th scope="col">Hostnaam</th>
                    <th scope="col">Status</th>
                    <th scope="col">Productie</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            {% for site in backend.get_sites %}
                <tr>
                    <td scope="row">{{ site.id }}</td>
                    <td class="break-word">{{ site.key }}</td>
                    <td class="break-word">{{ site.host }}</td>
                    <td>
                        {% if site.enabled %}
                            <i class="fa fa-check-circle text-success" aria-hidden="true"></i>
                        {% else %}
                            <i class="fa fa-times-circle text-danger" aria-hidden="true"></i>
                        {% endif %}
                    </td>
                    <td>
                        {% if site.env == "prod" %}
                            <i class="fa fa-check-circle text-success" aria-hidden="true"></i>
                        {% else %}
                            <i class="fa fa-times-circle text-secondary" aria-hidden="true"></i>
                        {% endif %}

                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <a href="{% url 'management:copy' backend.key site.id %}" class="btn btn-secondary"><i class="fa fa-copy" aria-hidden="true"></i></a>
                            {% if backend.is_writable %}
                                <a href="{% url 'management:edit' backend.key site.id %}" class="btn btn-secondary"><i class="fa fa-edit" aria-hidden="true"></i></a>
                                <a href="{% url 'management:delete' backend.key site.id %}" class="btn btn-secondary"><i class="fa fa-trash" aria-hidden="true"></i></a>
                            {% endif %}
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        Kies een omgeving aan de linkerzijde.
    {% endif %}
{% endblock %}