administration/urls.py
from django.urls import path
from . import views

app_name = 'administration'

urlpatterns = [
    path('<str:backend_key>/sites/', views.get_sites, name='sites'),
    path('<str:backend_key>/users/', views.get_user, name='users'),
    path('<str:backend_key>/admins/', views.get_admins, name='admins'),
    path('<str:backend_key>/', views.overview, name='overview'),
    path('', views.overview, name='overview'),
]

management/urls.py
from django.urls import path
from . import views

app_name = 'management'

urlpatterns = [
    path('<str:backend_key>/', views.overview, name='overview'),
    path('<str:backend_key>/copy/<int:site_id>/', views.copy, name='copy'),
    path('<str:backend_key>/edit/<int:site_id>/', views.edit, name='edit'),
    path('<str:backend_key>/delete/<int:site_id>/', views.delete, name='delete'),
    path('', views.overview, name='overview'),
    path('<str:backend_key>/admin_email_addresses', views.admin_email_addresses, name='admin_email_addresses')
]

pleio_control/urls.py
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib import admin

from two_factor.urls import urlpatterns as tf_urls
from management.urls import urlpatterns as management_urls
from administration.urls import urlpatterns as administration_urls

import core.views as core_views
import management.views as management_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', core_views.home, name='home'),
    path('tasks/', core_views.tasks, name='tasks'),
    path('tasks/status', core_views.task_status, name='task_status'),
    path('account/logout/', core_views.logout, name='logout'),
    path('', RedirectView.as_view(url='home')),
    path('', include(tf_urls)),
    path('management/', include('management.urls')),
    path('administration/', include('administration.urls')),
]

administration/models.py
from django.db import models

# Create your models here.

administration/forms.py
from django import forms
from django.core.exceptions import ValidationError


class UserForm(forms.Form):
    guid_email = forms.CharField(label='guid/email', max_length=100)

administration/views.py
import re
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.http import Http404
from django.shortcuts import render, redirect
from sqlalchemy.sql import and_, select
from management import elgg_models
from management.lib import Manager
from administration.utils import get_sites_by_organisation

from .forms import UserForm


def overview(request, backend_key=None):
    return render(request, 'administration/overview.html', _get_context(backend_key))


def get_user(request, backend_key):
    users = []
    if request.method == 'POST':
        form = UserForm(request.POST)

        if form.is_valid():
            try:
                guid = int((form.data['guid_email']).strip())
                email = ""
            except:
                email = form.data['guid_email'].strip()
                guid = 0
            if email:
                if not re.match(r"^.+@(\[?)[a-zA-Z0-9-.]+.([a-zA-Z]{2,3}|[0-9]{1,3})(]?)$", email):
                    messages.add_message(request, messages.ERROR, 'Geen geldige guid of email adres.')
                    return redirect('/administration/' + backend_key + '/users/')

            manager = Manager.Instance()

            source_backend = manager.backends[backend_key]
            sites = source_backend.get_sites()

            for site in sites:
                try:
                    source_site = source_backend.get_site(site['id'])
                except Exception:
                    continue

                if source_site.has_pleio_guid:
                    if guid:
                        query = select([elgg_models.users_entity_with_pleio_guid]).where(elgg_models.users_entity_with_pleio_guid.c.pleio_guid == guid)
                    else:
                        query = select([elgg_models.users_entity_with_pleio_guid]).where(elgg_models.users_entity_with_pleio_guid.c.email == email)
                    rows = source_site.connection.execute(query)
                else:
                    if guid:
                        query = select([elgg_models.users_entity_with_pleio_guid]).where(elgg_models.users_entity_with_pleio_guid.c.pleio_guid == guid)
                    else:
                        query = select([elgg_models.users_entity_with_pleio_guid]).where(elgg_models.users_entity_with_pleio_guid.c.email == email)
                    rows = source_site.connection.execute(query)

                for user in rows:

                    users.append({'email': user['email'], 'pleio_guid': user["pleio_guid"], 'site': site})
    else:
        form = UserForm()

    return render(request, 'administration/administration.html', {'form': form, 'users': users})


def get_sites(request, backend_key):
    users = []
    sites_data = []

    manager = Manager.Instance()

    source_backend = manager.backends[backend_key]
    sites = source_backend.get_sites()

    org_sites = get_sites_by_organisation(7)
    for site in sites:
        pleio_template = False
        organisation = ''
        organisation_type = ''
        site_type = ''
        try:
            source_site = source_backend.get_site(site['id'])
        except Exception:
            continue

        if site['key'] in org_sites.keys():
            organisation = org_sites[site['key']]['organisation']
            organisation_type = org_sites[site['key']]['organisation_type']
            site_type = org_sites[site['key']]['site_type']

        pleio_template = source_site.is_pleio_template_active()

        active_users = source_site.get_user_count(True)
        total_users = source_site.get_user_count()

        sites_data.append({'url': site['host'], 'site_type': site_type, 'organisation': organisation, 'organisation_type': organisation_type, 'total_users': total_users, "active_users": active_users,
                           'pleio_template': pleio_template, 'env': site['env']})

        del source_site

    return render(request, 'administration/sites.html', {'sites': sites_data})


def get_admins(request, backend_key):
    admins = []
    manager = Manager.Instance()

    source_backend = manager.backends[backend_key]
    sites = source_backend.get_sites()

    for site in sites:
        try:
            source_site = source_backend.get_site(site['id'])
        except Exception:
            continue

        pleio_template = source_site.is_pleio_template_active()
        
        if source_site.has_pleio_guid:
            query = select([elgg_models.users_entity_with_pleio_guid]).where(elgg_models.users_entity_with_pleio_guid.c.admin == 'yes')
            rows = source_site.connection.execute(query)
        else:
            query = select([elgg_models.users_entity_without_pleio_guid]).where(elgg_models.users_entity_without_pleio_guid.c.admin == 'yes')
            rows = source_site.connection.execute(query)

        for admin in rows:
            admins.append({'email': admin['email'], 'name': admin['name'], 'site': site['host'], 'pleio_template': pleio_template, 'env': site['env']})

        admins = list({v['email']:v for v in admins}.values())

    return render(request, 'administration/admins.html', {'admins': admins})


def _get_context(backend_key=None, site_id=None):
    manager = Manager.Instance()

    context = {
        'backends': manager.backends
    }

    if backend_key:
        try:
            context['backend'] = manager.backends[backend_key]
        except KeyError:
            raise Http404("Backend does not exist")

    if site_id:
        try:
            context['site'] = manager.backends[backend_key].get_site(site_id)
        except ObjectDoesNotExist:
            raise Http404("Site does not exist")

    return context

administration/templates/administration/_administration_base.html
{% extends '_base.html' %}

{% block content %}
    <div class="row">
        <div class="col-sm-2">
            {% include 'administration/partials/sidenav.html' %}
        </div>
        <div class="col-sm-10">
            {% block administration_content %}{% endblock %}
        </div>
    </div>
{% endblock %}

administration/templates/administration/administration.html
{% extends 'administration/_administration_base.html' %}

{% block administration_content %}

    <form action="." method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
    </form>

    <hr>

    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Site id</th>
                <th scope="col">Site host</th>
                <th scope="col">Site key</th>
                <th scope="col">Pleio guid</th>
                <th scope="col">Email</th>
                <th scope="col"></th>
            </tr>
        </thead>
    {% for user in users %}
        <tr>
            <td>{{ user.site.id }}</td>
            <td>{{ user.site.host }}</td>
            <td>{{ user.site.key }}</td>
            <td>{{ user.pleio_guid }}</td>
            <td>{{ user.email }}</td>
            <td></td>
        </tr>
    {% endfor %}
        </table>

{% endblock %}

administration/templates/administration/admins.html
{% extends 'administration/_administration_base.html' %}

{% block administration_content %}
<button class="mybutton">Download csv</button>
<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Site</th>
            <th scope="col">Env</th>
            <th scope="col">Pleio Template</th>
            <th scope="col"></th>
        </tr>
    </thead>
{% for admin in admins %}
    <tr>
        <td>{{ admin.name }}</td>
        <td>{{ admin.email }}</td>
        <td>{{ admin.site }}</td>
        <td>{{ admin.env }}</td>
        <td>{{ admin.pleio_template }}</td>
        <td></td>
    </tr>
{% endfor %}
    </table>

    <script>
        function download_csv(csv, filename) {
            var csvFile;
            var downloadLink;
        
            // CSV FILE
            csvFile = new Blob([csv], {type: "text/csv"});
        
            // Download link
            downloadLink = document.createElement("a");
        
            // File name
            downloadLink.download = filename;
        
            // We have to create a link to the file
            downloadLink.href = window.URL.createObjectURL(csvFile);
        
            // Make sure that the link is not displayed
            downloadLink.style.display = "none";
        
            // Add the link to your DOM
            document.body.appendChild(downloadLink);
        
            // Lanzamos
            downloadLink.click();
        }
        
        function export_table_to_csv(html, filename) {
            var csv = [];
            var rows = document.querySelectorAll("table tr");
            
            for (var i = 0; i < rows.length; i++) {
                var row = [], cols = rows[i].querySelectorAll("td, th");
                
                for (var j = 0; j < cols.length; j++) 
                    row.push(cols[j].innerText);
                
                csv.push(row.join(","));		
            }
        
            // Download CSV
            download_csv(csv.join("\n"), filename);
        }
        
        document.querySelector(".mybutton").addEventListener("click", function () {
            var html = document.querySelector("table").outerHTML;
            export_table_to_csv(html, "table.csv");
        });
        
    </script>

{% endblock %}

administration/templates/administration/overview.html
{% extends 'administration/_administration_base.html' %}

{% block administration_content %}
    {% if backend %}
        <div>
        <h3>{{ backend.name }}</h3>
        {% url 'administration:users' backend.key as users_url %}
        {% url 'administration:sites' backend.key as sites_url %}
        {% url 'administration:admins' backend.key as admins_url %}
        <br>
        <a href="{{ users_url }}">Zoek deelsites van gebruiker</a>
        <br><br>
        <a href="{{ sites_url }}">Deelsites</a>
        <br><br>
        <a href="{{ admins_url }}">Deelsitebeheerders</a>
    </div>
    {% else %}
        Kies een omgeving aan de linkerzijde.
    {% endif %}
{% endblock %}

administration/templates/administration/sites.html
{% extends 'administration/_administration_base.html' %}

{% block administration_content %}
<button class="mybutton">Download csv</button>
<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Url</th>
            <th scope="col">Type deelsite</th>
            <th scope="col">Organisatie</th>
            <th scope="col">Type organisatie</th>
            <th scope="col">Total users</th>
            <th scope="col">Active users</th>
            <th scope="col">Pleio Template</th>
            <th scope="col">Env</th>
            <th scope="col"></th>
        </tr>
    </thead>
{% for site in sites %}
    <tr>
        <td>{{ site.url }}</td>
        <td>{{ site.site_type }}</td>
        <td>{{ site.organisation }}</td>
        <td>{{ site.organisation_type }}</td>
        <td>{{ site.total_users }}</td>
        <td>{{ site.active_users }}</td>
        <td>{{ site.pleio_template }}</td>
        <td>{{ site.env }}</td>
        <td></td>
    </tr>
{% endfor %}
    </table>

<script>
function download_csv(csv, filename) {
    var csvFile;
    var downloadLink;

    // CSV FILE
    csvFile = new Blob([csv], {type: "text/csv"});

    // Download link
    downloadLink = document.createElement("a");

    // File name
    downloadLink.download = filename;

    // We have to create a link to the file
    downloadLink.href = window.URL.createObjectURL(csvFile);

    // Make sure that the link is not displayed
    downloadLink.style.display = "none";

    // Add the link to your DOM
    document.body.appendChild(downloadLink);

    // Lanzamos
    downloadLink.click();
}

function export_table_to_csv(html, filename) {
	var csv = [];
	var rows = document.querySelectorAll("table tr");
	
    for (var i = 0; i < rows.length; i++) {
		var row = [], cols = rows[i].querySelectorAll("td, th");
		
        for (var j = 0; j < cols.length; j++) 
            row.push(cols[j].innerText);
        
		csv.push(row.join(","));		
	}

    // Download CSV
    download_csv(csv.join("\n"), filename);
}

document.querySelector(".mybutton").addEventListener("click", function () {
    var html = document.querySelector("table").outerHTML;
	export_table_to_csv(html, "table.csv");
});

</script>

{% endblock %}