administration/urls.py
from django.urls import path
from . import views

app_name = 'administration'

urlpatterns = [
    path('<str:backend_key>/sites/', views.get_sites, name='sites'),
    path('<str:backend_key>/users/', views.get_user, name='users'),
    path('<str:backend_key>/admins/', views.get_admins, name='admins'),
    path('<str:backend_key>/', views.overview, name='overview'),
    path('', views.overview, name='overview'),
]

management/urls.py
from django.urls import path
from . import views

app_name = 'management'

urlpatterns = [
    path('<str:backend_key>/', views.overview, name='overview'),
    path('<str:backend_key>/copy/<int:site_id>/', views.copy, name='copy'),
    path('<str:backend_key>/edit/<int:site_id>/', views.edit, name='edit'),
    path('<str:backend_key>/delete/<int:site_id>/', views.delete, name='delete'),
    path('', views.overview, name='overview'),
    path('<str:backend_key>/admin_email_addresses', views.admin_email_addresses, name='admin_email_addresses')
]

pleio_control/urls.py
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib import admin

from two_factor.urls import urlpatterns as tf_urls
from management.urls import urlpatterns as management_urls
from administration.urls import urlpatterns as administration_urls

import core.views as core_views
import management.views as management_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', core_views.home, name='home'),
    path('tasks/', core_views.tasks, name='tasks'),
    path('tasks/status', core_views.task_status, name='task_status'),
    path('account/logout/', core_views.logout, name='logout'),
    path('', RedirectView.as_view(url='home')),
    path('', include(tf_urls)),
    path('management/', include('management.urls')),
    path('administration/', include('administration.urls')),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout as auth_logout
from django_celery_results.models import TaskResult
from django.core.paginator import Paginator
from django.contrib import messages
from django.http import JsonResponse
from celery.result import AsyncResult

def home(request):
    return render(request, 'index.html')

def tasks(request):
    tasks = TaskResult.objects.order_by('-id')
    paginator = Paginator(tasks, 25)

    page = request.GET.get('page')

    return render(request, 'tasks.html', {
        'tasks': paginator.get_page(page)
    })

def logout(request):
    messages.add_message(request, messages.SUCCESS, 'You logged out succesfully.')

    auth_logout(request)
    return redirect('/account/login/')

def task_status(request):
    task_id = request.GET.get('task_id')
    if task_id:
        async_result = AsyncResult(task_id)
        if async_result.ready():
            return JsonResponse({'finish': async_result.result})
    return JsonResponse({'finish': False})

core/templates/partials/logo.html
<svg viewBox="0 0 35 35" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="logo">
            <path d="M29.4,0 C32.5,0 35,2.5 35,5.6 L35,29.4 C35,32.5 32.5,35 29.4,35 L5.6,35 C2.5,35 0,32.5 0,29.4 L0,5.6 C0,2.5 2.5,0 5.6,0"
                id="Shape" fill="#535353"></path>
            <path d="M9,9 C10.2,7.8 12.1,7.8 13.2,9 L20,15.8 L21.3,14.5 L14.5,7.7 C12.6,5.8 9.6,5.8 7.7,7.7 C5.8,9.6 5.8,12.6 7.7,14.5 L9,15.9 L10.3,14.6 L9,13.2 C7.8,12 7.8,10.1 9,9"
                id="Shape" fill="#FFFFFF"></path>
            <path d="M26,26 C24.8,27.2 22.9,27.2 21.8,26 L15,19.2 L13.7,20.5 L20.5,27.3 C22.4,29.2 25.4,29.2 27.3,27.3 C29.2,25.4 29.2,22.4 27.3,20.5 L26,19.1 L24.7,20.4 L26.1,21.8 C27.2,23 27.2,24.9 26,26"
                id="Shape" fill="#FFFFFF"></path>
            <path d="M26,9 C27.2,10.2 27.2,12.1 26,13.2 L19.2,20 L20.5,21.3 L27.3,14.5 C29.2,12.6 29.2,9.6 27.3,7.7 C25.4,5.8 22.4,5.8 20.5,7.7 L19.1,9 L20.4,10.3 L21.8,9 C23,7.8 24.9,7.8 26,9"
                id="Shape" fill="#FFFFFF"></path>
            <path d="M9,26 C7.8,24.8 7.8,22.9 9,21.8 L15.8,15 L14.5,13.7 L7.7,20.5 C5.8,22.4 5.8,25.4 7.7,27.3 C9.6,29.2 12.6,29.2 14.5,27.3 L15.9,25.9 L14.6,24.6 L13.2,26 C12,27.2 10.1,27.2 9,26"
                id="Shape" fill="#FFFFFF"></path>
        </g>
    </g>
</svg>

core/templates/partials/modal.html
<!-- Modal -->
<div class="modal fade" id="{{ id }}" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">{{ title }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <pre><code>{{ content }}</code></pre>
            </div>
        </div>
    </div>
</div>

core/templates/partials/nav.html
{% load active %}
<nav class="navbar navbar-expand-md navbar-dark fixed-top">
    <a class="navbar-brand" href="{% url 'home' %}">
        {% include 'partials/logo.html' %}
        <span>Pleio control</span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {% active 'home' %}">
                <a class="nav-link" href="{% url 'home' %}">Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item {% active 'management' %}">
                <a class="nav-link" href="{% url 'management:overview' %}">Beheer</a>
            </li>
            <li class="nav-item {% active 'tasks' %}">
                <a class="nav-link" href="{% url 'tasks' %}">Achtergrondtaken</a>
            </li>
            <li class="nav-item {% active 'users' %}">
                <a class="nav-link" href="{% url 'administration:overview' %}">Administratie</a>
            </li>
        </ul>
        <ul class="navbar-nav justify-content-end">
            <li class="nav-item dropdown dropdown-menu-right">
                <a class="nav-link dropdown-toggle" id="user-menu" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">{{ request.user.get_full_name }}</a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="user-menu">
                    <a class="dropdown-item" href="/account/two_factor/">Account</a>
                    <a class="dropdown-item" href="/account/logout/">Uitloggen</a>
                </div>
            </li>
        </ul>
    </div>
</nav>